### PR TITLE
Add bug fix by by changing true to false and add clear function for i…

### LINKED ISSUE #3: Character Select Screen
The user should see:
   Text that says Choose Your Heroes (or something like it)
   2 empty character selection slots
   Search field and button to search by name
   Filter tab/buttons to filter creator and order by stats
   A scroll box with all available characters images and names

A user can select 2 different characters
   then a button to battle should appear where it said choose your fighters
  clicking the battle button should take the user to the battle screen

A User can select to view the character information for any available character
  this is left vague as FE can decide how these 2 selections are different

Image

### PR DESCRIPTION
**Pull request by BenHolden010**
## Description
[Provide a brief description of the changes introduced by this PR.]

Bug fixes to search/sort and added clear inputs

## Related Issue
[Link to any related issue(s) that this PR addresses, e.g., "Closes #123"]

## Checklist
- [x] I have reviewed the code changes.
- [x] I have tested this code.
- [ ] I have requested an update to the documentation.
- [x] I have checked for and resolved any merge conflicts.
- [x] I have assigned reviewers for this PR.

### CODE REVIEW

File: src/ApolloClient/client.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import {ApolloClient, InMemoryCache} from '@apollo/client';
 const client = new ApolloClient
 ({
   uri: 'https://fff-be-2e7913919a6b.herokuapp.com/graphql',
+  // uri: 'http://127.0.0.1:6969/graphql',
```
Comment (topher-nullset) [inline src/ApolloClient/client.js:5]: really good call!

File: src/components/App/App.js [hunk 2]
```diff
@@ -20,6 +20,12 @@ function App() {
   const [alignment, setAlignment] = useState("all")
   const [userInput, setUserInput] = useState('')
 
+  function clear(){
+    setPublisher("all")
+    setAlignment("all")
```
Comment (topher-nullset) [inline src/components/App/App.js:25]: nice clear state

**Review by topher-nullset — APPROVED** [review]
wowow im excited
